---
title: Effy Violet
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    permalink: "/:year/:month/:day/:title/"
    output: false
  shopcollections:
    title: Collections
    permalink: "/store/collections/:title/"
    output: true
  categories:
    title: Categories
    permalink: "/store/:categories/"
    output: true
  articles:
    title: Articles
    permalink: "/store/:categories/:title/"
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    has_comments: true
    image: ''
    description: ''
- scope:
    path: ''
    type: shopcollections
  values:
    layout: collection
    image: 
    hide: false
- scope:
    path: ''
    type: categories
  values:
    layout: categoriy
- scope:
    path: ''
    type: articles
  values:
    layout: article
    sizes:
    - S
    - M
    - L
currency: "â‚¬"
has_comments: true
disqus: https-esstudio-site
feedburner: https://feeds.feedburner.com/echosierrastudio
share:
- facebook
- twitter
- tumblr
- pinterest
- reddit
- google
- tumblr
- email
- pinterest
- linkedin
- xing
- whatsapp
- hackernews
- vk
- telegram
volledige-titel: Echo Sierra Studio
image_src: "/assets/img/image_src.png"
logo: "/assets/img/image_src.png"
keywords: Polyism Studio Sem Postma Echo Sierra Studio Web Software Code Programming
  Hub
exclude:
- vendor
description: Sustainable apparel line.
theme_color: "#fb5353"
baseurl: 
dribbble_username: ''
facebook_username: example
flickr_username: ''
github_username: ''
instagram_username: example
linkedin_username: ''
pinterest_username: example
twitter_username: example
youtube_username: ''
disqus_username: ''
googleplus_username: ''
rss: true
facebook:
  app_id: ''
  publisher: ''
  admins: ''
webmaster_verifications:
  google: ''
  bing: ''
  alexa: ''
  yandex: ''
  baidu: ''
twitter:
  username: esstudio_site
sass:
  style: compressed
  sass_dir: _sass
url: https://effyviolet.esstudio.site
enforce_ssl: effyviolet.esstudio.site
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
author: Eva van der Weide
designer: Eva van der Weide
lang: en
google_analytics: 
